<a href="https://colab.research.google.com/github/SAMashiyane/ANN_Salary/blob/main/ANN_S1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

In [17]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [18]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [19]:
X = dataset.iloc[:, 3:-1].values

In [20]:
y = dataset.iloc[:, -1].values

In [21]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [22]:
print(y)

[1 0 1 ... 1 1 0]


In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

In [25]:
X[:, 2] = le.fit_transform(X[:, 2])

In [26]:
print(X)
    

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
ann = tf.keras.models.Sequential()

In [34]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [35]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [36]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [37]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5823 - accuracy: 0.7576
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4598 - accuracy: 0.8015
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4372 - accuracy: 0.8126
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4297 - accuracy: 0.8149
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4244 - accuracy: 0.8151
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4207 - accuracy: 0.8192
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4171 - accuracy: 0.8220
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8231
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4108 - accuracy: 0.8270
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4077 - accura

In [39]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]
